### PR TITLE
Implement taggable part 2

### PR DESCRIPTION
**Pull request by JSFernandes**
Follow up to https://github.com/Dragonicity/tagger/pull/1

@Dragonicity May I ask you to please -not- merge this PR until we are in agreement that it meets the requirements?

At this point, requirements 1 and 2 should be implemented. I urge you to look at the tests added ([taggable_test.rb](https://github.com/Dragonicity/tagger/compare/main...JSFernandes:implement-taggable-part-2?expand=1#diff-b520b843e5dea3630cd5bae0f0aa56e7b0cdd069f541238776aeddbfa6b92003)) and see if it makes sense for `Taggable` to work like this.

The biggest issue in the air at this point is the ergonomics to get an `account_id` into a `Tagging`, and what methods like `tag_list=` should behave like.

And again, if you find Github cumbersome, feel free to suggest any other way in which we can collaborate.

### CODE REVIEW

**Comment by Dragonicity** [comment]
You cannot use setup and teardown in your Minitest tests e.g.

```
setup do
    @template = templates(...)
end

teardown do
  Rails.cache.clear
end
```

Which will save typing the MockTaggable class definition and called to MockTaggable.new in each test?

**Comment by Dragonicity** [comment]
Let's not worry about the Tagger polymorphic functionality - cannot see an obvious use for this as the tagged record will always have the tagger context.

**Comment by Dragonicity** [comment]
We can get rid of the Article model as well - it was only originally included as an example of the default way things were done.

**Comment by Dragonicity** [comment]
It seems that you did not receive the last email from me. The main points:

I do not use GitHub pull requests etc. as a matter of course as I am a solo developer. I do not use Jira either. I find the workflow design of these tools very counterintuitive. This is why I suggested email previously.

Ignore my comment about the tag_count optional context.

article.tags returns an AR relation. I think we are in agreement that the tags , reversed_meanings , and symbols fields in the templates table aren't really doing anything.

Yes. That was also the point of sending you the link to Dean's video which also dispenses with attributes on the models.

...Are templates transversal as well? Assuming that they are, and that only the taggings are tenant specific, I need to add methods to taggable that take an account as a parameter. ie with the current implementati…
… would also have to be able to accept a version with and without an account template . tags_list # returns all tags template . tags_list ( account ) # returns only the tags with taggings from a certain account

Yes this is the approach I assumed. No need to use apply_tags rather than tag_list though?

**Comment by JSFernandes** [comment]
@Dragonicity 

> You cannot use setup and teardown in your Minitest tests e.g.

In my experience, this makes tests harder to maintain and to diagnose when they fail. I like the current version where there are no shared variables between tests, and the entire context is can be read within the test. If you insist on maintaining a version with `setup` I can do it, but I wouldn't do it on an application which I plan on maintaining for a long time.

> Let's not worry about the Tagger polymorphic functionality - cannot see an obvious use for this as the tagged record will always have the tagger context.

> We can get rid of the Article model as well - it was only originally included as an example of the default way things were done.

>article.tags returns an AR relation. I think we are in agreement that the tags , reversed_meanings , and symbols fields in the templates table aren't really doing anything.

Sure, I'll take care of cleaning all of this up 👍 

> Yes this is the approach I assumed. No need to use apply_tags rather than tag_list though?

Not sure I understand. If I do `template.tag_list = "foo, bar"`, how do you expect the `account_id` to be passed?

PS: I might do a bit of work during the weekend. If I do, I'll register it on Monday for next week's timesheet.

**Comment by Dragonicity** [comment]
Leave the Minitest as it is I will change it later.
Do the apply_tags as you suggested.
The last piece is setting the locale-specific names when tags are added.
For this the code fragment:

```
Tag.i18n.find_or_initialize_by(name: tag_name)
```
will need to change a bit.

If a tag exists it must have a :name attribute set (which is what is currently checked) but conceivably may not have the e.g. name_fr attribute defined. For the latter we would need to set name_fr and then optionally loop through other available locales to find and set the value of these using an external API (which we could stub out for now). Arguably this could actually be instead a batch job that finds missing locale translations and adds them.

If a tag does not exist then we have to create it using the locale name passed to the method and then set the name_locale and name attributes accordingly. This implies that the current locale is a passed parameter. In the real application this is set from current_user.preferred_language as per the set_locale controller concern where I have commented this out - so it will be picked up from the params as specified in routes.rb or will be taken from I18n.default_locale. Let's think about the easiest way to do this before it is coded.

I am going to Finland on Thursday so we need to bring to a close work on this Wednesday at the latest. I will then be back in January and will think about what to do next.

**Comment by JSFernandes** [comment]
@Dragonicity The mobility gem automagically takes care of the querying based on the current locale. Thus, I don't think that `Tag.i18n.find_or_initialize_by(name: tag_name)` needs to change at all.

> For the latter we would need to set name_fr and then optionally loop through other available locales to find and set the value of these using an external API (which we could stub out for now). Arguably this could actually be instead a batch job that finds missing locale translations and adds them.

Yes, that's what point 3 in the requirements for tagger is all about. Speaking of which, may I add Sidekiq to this project? I don't understand if this is going to evolve to a fully fledged project, to a gem, or if you'll pluck code from this into another project. Thus, I can't make an informed decision on whether to make this agnostic to the background processor or to just plug in something tried and true.

> If a tag does not exist then we have to create it using the locale name passed to the method and then set the name_locale and name attributes accordingly. This implies that the current locale is a passed parameter. In the real application this is set from current_user.preferred_language as per the set_locale controller concern where I have commented this out - so it will be picked up from the params as specified in routes.rb or will be taken from I18n.default_locale. Let's think about the easiest way to do this before it is coded.

Again, doesn't the mobility gem just take care of this for us?

**Comment by Dragonicity** [comment]
Yes, you are right Mobility should handle this, but we still need to know the locale for some of the processing in part 3, but do not need this passed as a parameter.

Code will be plucked from this and inserted into the larger existing project (more correctly a rebuilt version of it given some recent changes in Rails). That project uses Redis and Sidekiq so OK to use this.

For the last paragraph above, Mobility does not entirely handle this. We can pick up the locale without it being a parameter, but need to pass the name_locale parameters to the create (or update) call if we are filling in missing values.

**Comment by JSFernandes** [comment]
@Dragonicity 

> We can pick up the locale without it being a parameter, but need to pass the name_locale parameters to the create (or update) call if we are filling in missing values.

No we don't. Lets use `Mobility.locale`.

I just added a commit with the logic to translate the tag on creation. It's using a fixed hardcoded translation. Regarding google translate, I see that they have 2 similar gems and that you already did some work with one of them. Can I just ignore that, plug whichever gem I prefer using my credentials, and then let you know if you need to do something in terms of credentials?

Furthermore, you may have noticed that this approach with Sidekiq is subject to a race condition: I may create a tag set as "books" in English, someone else creates a tag set as "Livros" in Portuguese "at the same time", and we may end up with duplicated tags. While I can make the code more defensive towards this, I think we will ultimately need a periodic cron job to catch these cases and resolve them as a single tag.

**Comment by Dragonicity** [comment]
We are saying the same thing about locales. Note that elsewhere I tend to use:

```
"name_#{Mobility.normalize_locale(locale)}"
```
No issue with using whichever approach is easiest for Google translate (which is also not well documented and seems to change more frequently than the Stripe API). I previously just proved that it works in practice.

The race condition is unlikely to occur in practice and can be caught with the validation:

```
valdiates_uniqueness_of :name
```
This arguably could be scoped to context.

I had thought about the need for a cron job to periodically check for missing translations.
In the eventuality of errors in the background process is this just updated in the log file typically?

**Comment by JSFernandes** [comment]
@Dragonicity 

> The race condition is unlikely to occur in practice and can be caught with the validation:

It is well known that rails validations don't completely eliminate race conditions, and only mitigate them. Furthermore, the scenario I described can still happen: while Mobility does an admirable job of trying to make such a validation work, it only validates for the current `Mobility.locale`.

>  In the eventuality of errors in the background process is this just updated in the log file typically?

This would be logged into whatever error tracker you are using ie Sentry/Honeybadger/Airbrake etc

**Comment by JSFernandes** [comment]
@Dragonicity I have now integrated google translate into `TagTranslationWorker`. You will need service account credentials for this. Please refer to https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-translate/AUTHENTICATION.md#creating-a-service-account Once you have the json with the keys run `export TRANSLATE_CREDENTIALS=path/to/keyfile.json` before opening your rails console.

I spent some free google cloud credits for this. Please provide me with the keys if you want me to do further work with google translate.

If you want to test the full tag flow locally, you can change line 45 of `tag.rb` to `TagTranslationWorker.new.perform(id, Mobility.locale.to_s)`, so that you can test everything synchronously without having to run Sidekiq.

I think that at this point nothing is missing from our agreed requirements. With that said, I will try to add tests to `TagTranslationWorker` tomorrow, but I can't guarantee that I have enough time. Let me know if something is missing.

**Comment by Dragonicity** [comment]
Had a look through the code now and looks to be complete and OK as per agreed requirements. I will try and look at it later today and tomorrow. Given the break will come back in January on next steps. Do you want me to merge pull request when I am happy with it?

**Comment by Dragonicity** [comment]
I wasn't aware of that race condition issue.

**Comment by JSFernandes** [comment]
@Dragonicity Yes, feel free to merge the pull request if you are happy with it.

As for January, let me know what you have scoped and defined when you can. I cannot guarantee availability by that time. Feel free to consider me for continuing the project, but please do not take my availability for granted.

**Pull request merged**
