### PR TITLE
Implement taggable

### PR DESCRIPTION
**Pull request by JSFernandes**
Still work in progress

### CODE REVIEW

**Comment by JSFernandes** [comment]
Hey @Dragonicity 

I started work on `Taggable`, and would like to double check a few things:

1. The class `tagged_with` doesn't really care about `taggable_on`, right? So, if I do `Template.tagged_with("foo")`, it will find my all `Template`s which have a tag named foo, regardless of the context in which it is applied.
2. Regarding `tag_count`, this does depend on `taggable_on`. So, for `Template`, I would have class methods such as `symbol_count` and `reversed_meaning_count`. The result would be an AR query with a mapping of `tag_id` to a count. Sounds right?
3. I am a bit confused about what is expected from the instance methods. `Template` has a `symbols` string field on the database. Should `Template.find(1).symbols` not search the database for taggings with the `symbols` context?

**Comment by JSFernandes** [comment]
@Dragonicity I have now implemented the requested methods on `Taggable`. It is not 100% clear to me whether I implemented `tag_count` as intended. It currently returns a hash mapping `tag_id` to a `count`, for that given context, for that given `taggable`.

Two non meta programming rails things:

1. I have removed the `account_id` requirement from `Tagging`. Otherwise, `tag_list=` would need to take an account as a parameter for the tagging
2. Creating a new `Template` with the tags directly isn't working due to the non-null validations on `Tagging`. ie `Template.create!(body: "lorem ispum", symbol_list: "emoji, hiragana")` will fail when creating the taggings since the associations aren't persisted yet.

I will clean up the validations from the second point and start working on tests when I pick this up again, which should be on Thursday or Friday.

**Review by Dragonicity — APPROVED** [review]

**Review by Dragonicity — COMMENTED** [review]
The has_many :taaings and has_many :tags, through: :taggings are picked up from the concern by using taggable_on :tags

Presumably the include taggable can be included in the application_record.rb (as controller concerns are including in application_controller.rb)?

**Review by Dragonicity — COMMENTED** [review]
Why is the self.tagged_with not also in taggable.rb?

**Comment by Dragonicity** [comment]
> Hey @Dragonicity
> 
> I started work on `Taggable`, and would like to double check a few things:
> 
> 1. The class `tagged_with` doesn't really care about `taggable_on`, right? So, if I do `Template.tagged_with("foo")`, it will find my all `Template`s which have a tag named foo, regardless of the context in which it is applied.
> 2. Regarding `tag_count`, this does depend on `taggable_on`. So, for `Template`, I would have class methods such as `symbol_count` and `reversed_meaning_count`. The result would be an AR query with a mapping of `tag_id` to a count. Sounds right?
> 3. I am a bit confused about what is expected from the instance methods. `Template` has a `symbols` string field on the database. Should `Template.find(1).symbols` not search the database for taggings with the `symbols` context?

I think it should be tagged_with(name: name, context: "symbols") with search on all contexts if no context is provided?
tag_count would again presumably have an optional context?
The whole question of how the model attributes relates to methods e.g. tags to tag_list (and model.tags) has always seemed odd. We allow the user to change the tags which is then reflected in changes to the tags and taggings which is usually done by trying to make updates or just deleting all the current taggings and replacing them with the ones from the params hash for the attribute concerned. This is all a bit clunky. I would expect @article.tags to return array of AR instances from the Tag model (for a tag context).

**Review by Dragonicity — COMMENTED** [review]
The issue here is that account_id is the identifier used for tenant in a multi-tenant app. Tags are usually seen as transversal (debatable) and taggings as tenant specific. You may still end up with some tags visible to a tenant created by another tenant but at least their taggings are specific to their account_id.

**Review by Dragonicity — COMMENTED** [review]
Not entirely sure what the  has_many tagging_type method is doing.

**Review by Dragonicity — COMMENTED** [review]
is the tagged_with(name) not in the concern?

**Comment by Dragonicity** [comment]
I find using GitHub really cumbersome!

**Comment by Dragonicity** [comment]
Here's a more recent video that shows tagging without the instance variables: https://www.youtube.com/watch?v=03enr4NNgLI&t=324s

**Comment by JSFernandes** [comment]
@Dragonicity Thank you for looking into this. However, I was not expecting you to merge the PR. I had opened it as a draft so that we could discuss the code and the expectations while directly referring to the code we are discussing.

> Presumably the include taggable can be included in the application_record.rb (as controller concerns are including in application_controller.rb)?

I am not sure what you mean by this, or what advantages you are expecting to gain. We don't want to include these methods on every single model, and taggable doesn't really do anything until `tagged_with` is called.

> Why is the self.tagged_with not also in taggable.rb?

It is https://github.com/Dragonicity/tagger/pull/1/files#diff-d00ecb6e72fdb6a19997d6a2c06c4d7f9055d5c966708524ea7f2c6bc4a3e670R15

> I think it should be tagged_with(name: name, context: "symbols") with search on all contexts if no context is provided?

Yeah, that makes sense. I'll apply it 👍 

>  tag_count would again presumably have an optional context?

I didn't create a `tag_count` method, and instead created dynamic methods based on the context. Thus, `Template` has the `tag_count`, `reversed_meaning_count`, and `symbol_count` methods. Sounds good?

>  The whole question of how the model attributes relates to methods e.g. tags to tag_list (and model.tags) has always seemed odd. We allow the user to change the tags which is then reflected in changes to the tags and taggings which is usually done by trying to make updates or just deleting all the current taggings and replacing them with the ones from the params hash for the attribute concerned. This is all a bit clunky. I would expect @article.tags to return array of AR instances from the Tag model (for a tag context).

`article.tags` returns an AR relation. I think we are in agreement that the `tags`, `reversed_meanings`, and `symbols` fields in the `templates` table aren't really doing anything.

> The issue here is that account_id is the identifier used for tenant in a multi-tenant app. Tags are usually seen as transversal (debatable) and taggings as tenant specific. You may still end up with some tags visible to a tenant created by another tenant but at least their taggings are specific to their account_id.

Are templates transversal as well? Assuming that they are, and that only the taggings are tenant specific, I need to add methods to `taggable` that take an account as a parameter. ie with the current implementation I can do:

```ruby
  template.tag_list = "foo, bar"
```

If we now need to take an account, then this would become something like

```ruby
  template.apply_tags("foo, bar", account)
```

Does this seem like an acceptable usage?  Furthermore, for fetch methods we would also have to be able to accept a version with and without an account

```ruby
  template.tags_list # returns all tags
  template.tags_list(account) # returns only the tags with taggings from a certain account
```

> Not entirely sure what the has_many tagging_type method is doing.

It defines a `has_many` relationship for the taggings context type. So in `Template` you can do `template.symbol_taggings`, `template-reverse_meaning_taggings` etc. It also facilitates the `has_many` defined below it. Doing this through AR gives us powerful tools such as the ability to use joins or includes in queries with our tagging context types ie `Template.all.includes(:reverse_meanings)`

> I find using GitHub really cumbersome!

Do you have any other suggestions? I must admit that I find your use of it odd, having merged the PR so early, not commenting on the code directly, and spreading your comments in this way. Let me know if you'd like to collaborate in another way.

> Here's a more recent video that shows tagging without the instance variables: https://www.youtube.com/watch?v=03enr4NNgLI&t=324s

I'm not sure what to take away from this. It's very much what `"#{tag_type}_list="` is already doing.

**Pull request merged**
